experiment_name: airline_delay_2015_full_classification

dataset:
  source: csv
  path: datasets/airline-delay-and-cancellation-data/2015_sample_500k.csv
  target_column: CANCELLED

models:
  - logistic_regression
  - knn
  - random_forest
  - svm
  - xgboost
  - lightgbm_classifier

preprocessing:
  scale: standard
  imputation: median
  encoding: one_hot

cv:
  strategy: stratified_kfold
  folds: 3

tags:
  - airline
  - "2015"
  - full
  - classification
